---


exp:  stainer_basic_cmp/KoopmanUNet_CA_GA
seed: 42

loader:
  norm_method: global_minmax
  train_batch: 1
  val_batch:   1
  num_workers: 0
  pin_memory:  true

model:
  name: KoopmanUNet

loss:
  name: MSE

optimizer:
  name: AdamW
  params:
    lr:           0.001
    betas:        [0.5, 0.9]
    weight_decay: 0.05

scheduler:
  min_lr: 0.0
  warmup: 50

trainer:
  epochs:     100
  accum_iter: 1
  diffaug:    false
  ema:        true
  low_weight: 1.0
  apply_cmp:  true
  start_cmp:  50
  ckpt_freq:  50
  print_freq: 300


...